### ISSUE TITLE
Scale for multiple cameras and clients

### ISSUE THREAD

**Issue by kevinzezel** [egeakman/mjpeg-streamer#11]
Hi,

Great work! Thanks for sharing your project.

I'm working with multiple RTSP streams and using ffmpeg and Flask to generate an MJPEG stream. However, I'm facing challenges scaling this solution for multiple clients. I really like your project and would like to explore using it.

For handling multiple cameras, I'm currently creating a separate server:port combination for each camera. Is this the best approach? How can I scale this for multiple clients? Could Kubernetes be a good solution?

Regards

**Comment by egeakman** [comment]
Hi @kevinzezel, it's nice to hear that you liked the project!

You can have multiple sources in a single server and a port (see [this example](https://github.com/egeakman/mjpeg-streamer/blob/main/examples/multiple_sources.py)).

How many clients are we talking about?

This project is meant for home and small network use cases. I haven't tested it on large/public networks and more than a few clients, thus I can't guarantee that it will work or be secure in those cases. However, I'd love to try new things out!

By the way, I am working on [a new, more efficient structure](https://github.com/egeakman/mjpeg-streamer/pull/6). So stay tuned!

**Comment by egeakman** [comment]
Closing as stale
